//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.Email.Exchange {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.Email.Exchange.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложения, если несколько файлов то перечислять через ,.
        /// </summary>
        internal static string Attachments_Description {
            get {
                return ResourceManager.GetString("Attachments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вложения.
        /// </summary>
        internal static string Attachments_Name {
            get {
                return ResourceManager.GetString("Attachments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Те кому придет копия письма.
        /// </summary>
        internal static string BCC_Description {
            get {
                return ResourceManager.GetString("BCC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копия.
        /// </summary>
        internal static string BCC_Name {
            get {
                return ResourceManager.GetString("BCC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория письма.
        /// </summary>
        internal static string Categories_Description {
            get {
                return ResourceManager.GetString("Categories_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории письма.
        /// </summary>
        internal static string Categories_Name {
            get {
                return ResourceManager.GetString("Categories_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Те кто получит скрытую копию.
        /// </summary>
        internal static string CC_Description {
            get {
                return ResourceManager.GetString("CC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрытая копия.
        /// </summary>
        internal static string CC_Name {
            get {
                return ResourceManager.GetString("CC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен вашей компании, если есть.
        /// </summary>
        internal static string Domain_Description {
            get {
                return ResourceManager.GetString("Domain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домен.
        /// </summary>
        internal static string Domain_Name {
            get {
                return ResourceManager.GetString("Domain_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Письма.
        /// </summary>
        internal static string EmailMessages_Name {
            get {
                return ResourceManager.GetString("EmailMessages_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Куда сохранить.
        /// </summary>
        internal static string FolderToSave_Name {
            get {
                return ResourceManager.GetString("FolderToSave_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить письма из укзанной папки.
        /// </summary>
        internal static string GetMessage_Description {
            get {
                return ResourceManager.GetString("GetMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить письма.
        /// </summary>
        internal static string GetMessage_Name {
            get {
                return ResourceManager.GetString("GetMessage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело письма в формате HTML?.
        /// </summary>
        internal static string Html_Description {
            get {
                return ResourceManager.GetString("Html_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело письма в виде HTML.
        /// </summary>
        internal static string Html_Name {
            get {
                return ResourceManager.GetString("Html_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин для подключения к сервисам без домена.
        /// </summary>
        internal static string Login_Description {
            get {
                return ResourceManager.GetString("Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        internal static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во писем.
        /// </summary>
        internal static string MailCount_Name {
            get {
                return ResourceManager.GetString("MailCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пометить как прочитанное.
        /// </summary>
        internal static string MarkAsRead_Name {
            get {
                return ResourceManager.GetString("MarkAsRead_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пометить как непрочитанное.
        /// </summary>
        internal static string MarkAsUnRead_Name {
            get {
                return ResourceManager.GetString("MarkAsUnRead_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправленное письмо.
        /// </summary>
        internal static string Message_Name {
            get {
                return ResourceManager.GetString("Message_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещает письмо из одной папки в другую.
        /// </summary>
        internal static string MoveMail_Description {
            get {
                return ResourceManager.GetString("MoveMail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить письмо.
        /// </summary>
        internal static string MoveMail_Name {
            get {
                return ResourceManager.GetString("MoveMail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить в корзину.
        /// </summary>
        internal static string MoveToDeleteItems_Name {
            get {
                return ResourceManager.GetString("MoveToDeleteItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка куда будет перемещено письмо.
        /// </summary>
        internal static string NewFolderName_Description {
            get {
                return ResourceManager.GetString("NewFolderName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка назначения.
        /// </summary>
        internal static string NewFolderName_Name {
            get {
                return ResourceManager.GetString("NewFolderName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала новые.
        /// </summary>
        internal static string NewMail_Name {
            get {
                return ResourceManager.GetString("NewMail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка где будет происходить поиск.
        /// </summary>
        internal static string OldFolderName_Description {
            get {
                return ResourceManager.GetString("OldFolderName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходная папка.
        /// </summary>
        internal static string OldFolderName_Name {
            get {
                return ResourceManager.GetString("OldFolderName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль для подключения к сервисам.
        /// </summary>
        internal static string Password_Description {
            get {
                return ResourceManager.GetString("Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string Password_Name {
            get {
                return ResourceManager.GetString("Password_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатели, если несколько человек, то перечислять через ;.
        /// </summary>
        internal static string Recipients_Description {
            get {
                return ResourceManager.GetString("Recipients_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получатели.
        /// </summary>
        internal static string Recipients_Name {
            get {
                return ResourceManager.GetString("Recipients_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить копию письма?.
        /// </summary>
        internal static string SaveCopy_Description {
            get {
                return ResourceManager.GetString("SaveCopy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить копию после отправки.
        /// </summary>
        internal static string SaveCopy_Name {
            get {
                return ResourceManager.GetString("SaveCopy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться к Exchange и отправить письмо.
        /// </summary>
        internal static string SendMai_Description {
            get {
                return ResourceManager.GetString("SendMai_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить сообщение Exchange.
        /// </summary>
        internal static string SendMail_Name {
            get {
                return ResourceManager.GetString("SendMail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экземпляр отправленного письма.
        /// </summary>
        internal static string SendMessage_Description {
            get {
                return ResourceManager.GetString("SendMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема письма.
        /// </summary>
        internal static string Subject_Description {
            get {
                return ResourceManager.GetString("Subject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема письма.
        /// </summary>
        internal static string Subject_Name {
            get {
                return ResourceManager.GetString("Subject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст сообщения.
        /// </summary>
        internal static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело письма.
        /// </summary>
        internal static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только непрочитанные.
        /// </summary>
        internal static string UnRead_Name {
            get {
                return ResourceManager.GetString("UnRead_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL подключения без ewc... и https, и owa.
        /// </summary>
        internal static string URL_Description {
            get {
                return ResourceManager.GetString("URL_Description", resourceCulture);
            }
        }
    }
}
